# Generated by Django 5.2.4 on 2025-11-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_a4dd5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_75b83f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_e4c995_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='payment_transaction',
        ),
        migrations.RemoveField(
            model_name='notificationchannel',
            name='user',
        ),
    ]
