# Generated by Django 5.2.4 on 2025-11-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pesapal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesapalorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesapalorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
