# Generated by Django 5.2.4 on 2025-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_foodimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlisting',
            name='distance',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='country',
            field=models.CharField(default='Uganda', help_text='Country name', max_length=100),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='location',
            field=models.CharField(help_text='Pickup location address', max_length=300),
        ),
    ]
