# Generated by Django 4.2.11 on 2025-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_foodlisting_distance_foodlisting_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='foodlisting',
            name='city',
        ),
        migrations.RemoveField(
            model_name='foodlisting',
            name='country',
        ),
        migrations.RemoveField(
            model_name='foodlisting',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from user in kilometers', max_digits=8, null=True),
        ),
    ]
