# Generated by Django 5.2.4 on 2025-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_remove_foodimage_image_remove_foodlisting_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlisting',
            name='distance',
        ),
    ]
