# Generated by Django 5.2.4 on 2025-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_foodlisting_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from user in kilometers', max_digits=8, null=True),
        ),
    ]
